-- ============================================================================
-- Blinkit Data Warehouse - Table DDLs
-- Database: BLINKIT_DW | Schema: RAW
-- ============================================================================

-- 1. Orders table
CREATE OR REPLACE TABLE BLINKIT_DW.RAW.BLINKIT_ORDERS (
    ORDER_ID            NUMBER(12,0) NOT NULL,
    CUSTOMER_ID         NUMBER(12,0) NOT NULL,
    ORDER_DATE          TIMESTAMP_NTZ(9),
    PROMISED_DELIVERY_TIME TIMESTAMP_NTZ(9),
    ACTUAL_DELIVERY_TIME   TIMESTAMP_NTZ(9),
    DELIVERY_STATUS     VARCHAR(50),
    ORDER_TOTAL         NUMBER(12,2),
    PAYMENT_METHOD      VARCHAR(30),
    DELIVERY_PARTNER_ID NUMBER(12,0),
    STORE_ID            NUMBER(12,0),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);

-- 2. Order Items table
CREATE OR REPLACE TABLE BLINKIT_DW.RAW.BLINKIT_ORDER_ITEMS (
    ORDER_ID    NUMBER(12,0) NOT NULL,
    PRODUCT_ID  NUMBER(12,0) NOT NULL,
    QUANTITY    NUMBER(10,0),
    UNIT_PRICE  NUMBER(10,2),
    TOTAL_PRICE NUMBER(12,2) AS (QUANTITY * UNIT_PRICE),
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);

-- 3. Delivery Performance table
CREATE OR REPLACE TABLE BLINKIT_DW.RAW.BLINKIT_DELIVERY_PERFORMANCE (
    ORDER_ID              NUMBER(12,0) NOT NULL,
    DELIVERY_PARTNER_ID   NUMBER(12,0),
    PROMISED_TIME         TIMESTAMP_NTZ(9),
    ACTUAL_TIME           TIMESTAMP_NTZ(9),
    DELIVERY_TIME_MINUTES NUMBER(6,2) AS (TIMESTAMPDIFF(MINUTE, PROMISED_TIME, ACTUAL_TIME)),
    DISTANCE_KM           NUMBER(6,2),
    DELIVERY_STATUS       VARCHAR(50),
    REASONS_IF_DELAYED    VARCHAR(200),
    CONSTRAINT PK_DELIVERY PRIMARY KEY (ORDER_ID)
);

-- 4. Marketing Performance table
CREATE OR REPLACE TABLE BLINKIT_DW.RAW.BLINKIT_MARKETING_PERFORMANCE (
    CAMPAIGN_ID       NUMBER(10,0) NOT NULL,
    CAMPAIGN_NAME     VARCHAR(200),
    DATE              DATE,
    TARGET_AUDIENCE   VARCHAR(100),
    CHANNEL           VARCHAR(50),
    IMPRESSIONS       NUMBER(12,0),
    CLICKS            NUMBER(12,0),
    CONVERSIONS       NUMBER(12,0),
    SPEND             NUMBER(12,2),
    REVENUE_GENERATED NUMBER(12,2),
    ROAS              NUMBER(5,2),
    CONSTRAINT PK_MARKETING PRIMARY KEY (CAMPAIGN_ID, DATE)
);
